[[https://melpa.org/#/citar-denote][file:https://melpa.org/packages/citar-denote-badge.svg]]    [[https://stable.melpa.org/#/citar-denote][file:https://stable.melpa.org/packages/citar-denote-badge.svg]]

A minor-mode integrating the Emacs [[https://github.com/emacs-citar/citar][Citar]] and [[https://protesilaos.com/emacs/denote][Denote]] packages to enable managing bibliographic notes and citations.

For more information read the [[http://lucidmanager.org/productivity/citar-denote-managing-bibliographic-notes-in-emacs/][citar-denote manual]] as part of the /Emacs Writing Studio/.

* Installation and configuration
This package is available in MELPA. You can install it with  John Wiegley's [[https://github.com/jwiegley/use-package][Use-Package]]. The example below includes all configurable variables and the package defaults. You can either remove these entries or configure to your preferences. All these variables are also configurable with the customisation menu. The suggested keyboard bindings use the /Emacs Writing Studio/ keybinding prefix.

#+begin_src elisp
  (use-package citar-denote
    :custom
    ;; Use package defaults
    (citar-open-always-create-notes nil)
    (citar-denote-file-type 'org)
    (citar-denote-subdir nil)
    (citar-denote-keyword "bib")
    (citar-denote-use-bib-keywords nil)
    (citar-denote-title-format "title")
    (citar-denote-title-format-authors 1)
    (citar-denote-title-format-andstr "and")
    :init
    (citar-denote-mode)
    ;; Bind all available commands
    :bind (("C-c w c c" . citar-create-note)
           ("C-c w c n" . citar-denote-open-note)
           ("C-c w c d" . citar-denote-dwim)
           ("C-c w c e" . citar-denote-open-reference-entry)
           ("C-c w c a" . citar-denote-add-citekey)
           ("C-c w c k" . citar-denote-remove-citekey)
           ("C-c w c r" . citar-denote-find-reference)
           ("C-c w c f" . citar-denote-find-citation)
           ("C-c w c l" . citar-denote-link-reference)))
#+end_src

* Citar Configuration
You can use the standard Citar configuration, and there is no need to change any settings (including templates) related to bibliographic notes, as Citar-Denote takes over the note-taking functionality in Citar. 

* Acknowledgements
This code would only have existed with the help of Protesilaos Stavrou, developer of Denote and Citar developer Bruce D'Arcus.

In addition, Joel Lööw and Noboru Ota added significant contributions, without which this package would be useless. Finally, Guillermo Navarro, Colin McLear, Lucas Gruss, Adrian Adermon, and Jonathan Sahar provided valuable suggestions to extend the functionality.

Feel free to raise an issue here on GitHub if you have any questions or find bugs or suggestions for enhanced functionality.
