[[https://melpa.org/#/citar-denote][file:https://melpa.org/packages/citar-denote-badge.svg]]    [[https://stable.melpa.org/#/citar-denote][file:https://stable.melpa.org/packages/citar-denote-badge.svg]]

A minor-mode integrating the Emacs [[https://github.com/emacs-citar/citar][Citar]] and [[https://protesilaos.com/emacs/denote][Denote]] packages to enable create managing bibliographic notes and citations.

For more information read the [[file:citar-denote.org][Citar-Denote Manual]] in this repository.

* Installation and configuration
This package is available in MELPA. The example below includes all configurable variables and the package defaults. You can either remove these entries or configure to your preferences.

#+begin_src elisp :results none
  (use-package citar-denote
    :demand t ;; Ensure minor mode is loaded
    :custom
    ;; Allow multiple notes per bibliographic entry
    (citar-open-always-create-notes nil)
    ;; Package defaults
    (citar-denote-file-type 'org)
    (citar-denote-subdir nil)
    (citar-denote-signature nil)
    (citar-denote-template nil)
    (citar-denote-keyword "bib")
    (citar-denote-use-bib-keywords nil)
    (citar-denote-title-format "title")
    (citar-denote-title-format-authors 1)
    (citar-denote-title-format-andstr "and")
    :config
    (citar-denote-mode)
    ;; Bind all available commands
    :bind (("C-c w c" . citar-create-note)
           ("C-c w n" . citar-denote-open-note)
           ("C-c w d" . citar-denote-dwim)
           ("C-c w e" . citar-denote-open-reference-entry)
           ("C-c w a" . citar-denote-add-citekey)
           ("C-c w k" . citar-denote-remove-citekey)
           ("C-c w n" . citar-denote-no-bibliography)
           ("C-c w r" . citar-denote-find-reference)
           ("C-c w l" . citar-denote-link-reference)
           ("C-c w f" . citar-denote-find-citation)
           ("C-c w x" . citar-denote-nocite)
           ("C-c w y" . citar-denote-cite-nocite)))
#+end_src

You can use the standard configurations for Citar and Denote. Citar-Denote takes over the note-taking functionality in Citar.

The =init.el= file in this =test= folder of this repository provides a minimum working example for testing. It requires [[https://github.com/jwiegley/use-package][use-package]] to be available (built-in from Emacs 29).

* Acknowledgements
This code would only have existed with the help of Protesilaos Stavrou, developer of Denote and Citar developer Bruce D'Arcus.

In addition, Joel Lööw and Noboru Ota added significant contributions, without which this package would be useless. Finally, Troy Figiel , Taha Aziz Ben Ali, Guillermo Navarro, Colin McLear, Lucas Gruss, Adrian Adermon, and Jonathan Sahar provided valuable suggestions to extend the functionality.

Feel free to raise an issue here on GitHub if you have any questions or find bugs or suggestions for enhanced functionality.

* Change Log
** Version 2.1
- Bug fixes in regex to find citations.
- New function: ~citar-denote-no-bibliography~ lists all citations that do not appear in the global bibliography in the =*Messages*= buffer.
- Updated function documentation.
- Included Texinfo manual.
  
** Version 2.02
- Improved function docstrings
- Updated example config

** Version 2.0.1
- Updated minor mode definition
- Updated =readme.org= and =minimum-config.el= to define order or installation

** Version 2.0
- Commenced Change Log.
- Updated all functions for full compatibility with Denote 2.2
- Added =minimum-config.el= to provide minimal configuration example.
- Added ~citar-denote-signature~ variable to add signatures for new bibliographic notes. When entering an empty string as signature, the citation key is used as signature.
- The ~citar-denote-template~ variable defines whether a not template is used.
- Added ~citar-denote-nocite~ function to open Citar completion menu with all bibliographic entries neither cited nor referenced in any Denote file. This negates the need for ~citar-denote-reference-nocite~ because notes can be created from within the Citar menu.
- Existing reference removed from Citar completion menu when adding a new reference to a note.
- Fixed a bug in ~citar-denote-add-citekey~ and ~citar-denote-remove-citekey~ when using multiple file types.
- Removed false positives from ~citar-denote--extract-citations~.
- Behaviour of ~citar-denote-use-bib-keywords~ changed. When not-nil, don't prompt for keywords and only use those in the bibliography.
- The ~citar-denote-keyword~ ("bib") is removed from the keyword completion menu to avoid confusion.
- Resolved bug for when ~citar-denote-keyword~ is =nil=.
- ~citar-denote-link-reference~ check that file is a Denote file and fixed linking bug.
- Added ~citar-denote--select-file-using-title~ to select a Denote filename using their title in the completion menu.
- When only one candidate available in ~citar-denote-find-citation~, skip the section menu.

** Version 1.8
- Fixing bugs and improve package documentation.
- Marked private functions with double dash
- Updated ~citar-denote-citekey-regex~ to detect citations with multiple entries
- Updated Citar-Denote manual in [[https://lucidmanager.org/productivity/citar-denote-managing-bibliographic-notes-in-emacs/][Emacs Writing Studio]].

** Version 1.7
- Code refactoring and pretty-printing
- Updated function documentation
- Bug fix to ~citar-denote-remove-citekey~
- Package documentation update
- Code refactoring
- Added ~citar-denote-link-reference~ to insert a Denote link to an existing bibliographic note.
- Added ~citar-denote-find-citation~ to find a citation in your Denote files.
