[[https://melpa.org/#/citar-denote][file:https://melpa.org/packages/citar-denote-badge.svg]]    [[https://stable.melpa.org/#/citar-denote][file:https://stable.melpa.org/packages/citar-denote-badge.svg]]

Citar-Denote is a minor-mode integrating the Emacs [[https://github.com/emacs-citar/citar][Citar]] and [[https://protesilaos.com/emacs/denote][Denote]] packages to enable create managing bibliographic notes and citations.

For more information read the [[file:citar-denote.org][Citar-Denote Manual]] in this repository with =C-h R= (~info-display-manual~) and select =citar-denote=.

* Change Log
** Version 2.2.2
- Integration with ~citar-embark~.
 - Added ~citar-denote-cite-includes-reference~ variable to include referneces when searching for citations.
- Updated manual and function docstrings.
- Bug fixes (compilation errors)
  
** Version 2.2.1
- ~citar-denote-template~ has additional options:
  - =nil=: No template
  - =t=: Ask or a template
  - =string=: Name of the default template for literature notes
- Updated manual
  
** Version 2.2
- ~citar-denote-subdir~ has additional options:
  - =nil=: No subdirectory
  - =t=: Ask for subdirectory
  - =string= : When using any string, save in a subdirectory with that name under ~denote-directory~
- Modified behaviour of ~citar-denote-signature~. Users can choose between manually adding a signature or using citation key without prompting.
    
** Version 2.1.2
- Removed lighter string to not clobber the mode line
- Bug fixed when using non-standard ~citar-denote-keyword~
  
** Version 2.1.1
- Updated the manual
- Minor code updates
  
** Version 2.1
- Included Texinfo manual.
- Bug fixes in regex to find citations.
- New function: ~citar-denote-no-bibliography~ lists all citations that do not appear in the global bibliography in the =*Messages*= buffer.
- Updated function documentation.
  
** Version 2.02
- Improved function docstrings
- Updated example config

** Version 2.0.1
- Updated minor mode definition
- Updated =readme.org= and =minimum-config.el= to define order or installation

** Version 2.0
- Commenced Change Log.
- Updated all functions for full compatibility with Denote 2.2
- Added =minimum-config.el= to provide minimal configuration example.
- Added ~citar-denote-signature~ variable to add signatures for new bibliographic notes. When entering an empty string as signature, the citation key is used as signature.
- The ~citar-denote-template~ variable defines whether a not template is used.
- Added ~citar-denote-nocite~ function to open Citar completion menu with all bibliographic entries neither cited nor referenced in any Denote file. This negates the need for ~citar-denote-reference-nocite~ because notes can be created from within the Citar menu.
- Existing reference removed from Citar completion menu when adding a new reference to a note.
- Fixed a bug in ~citar-denote-add-citekey~ and ~citar-denote-remove-citekey~ when using multiple file types.
- Removed false positives from ~citar-denote--extract-citations~.
- Behaviour of ~citar-denote-use-bib-keywords~ changed. When not-nil, don't prompt for keywords and only use those in the bibliography.
- The ~citar-denote-keyword~ ("bib") is removed from the keyword completion menu to avoid confusion.
- Resolved bug for when ~citar-denote-keyword~ is =nil=.
- ~citar-denote-link-reference~ check that file is a Denote file and fixed linking bug.
- Added ~citar-denote--select-file-using-title~ to select a Denote filename using their title in the completion menu.
- When only one candidate available in ~citar-denote-find-citation~, skip the section menu.

** Version 1.8
- Fixing bugs and improve package documentation.
- Marked private functions with double dash
- Updated ~citar-denote-citekey-regex~ to detect citations with multiple entries
- Updated Citar-Denote manual in [[https://lucidmanager.org/productivity/citar-denote-managing-bibliographic-notes-in-emacs/][Emacs Writing Studio]].

** Version 1.7
- Code refactoring and pretty-printing
- Updated function documentation
- Bug fix to ~citar-denote-remove-citekey~
- Package documentation update
- Code refactoring
- Added ~citar-denote-link-reference~ to insert a Denote link to an existing bibliographic note.
- Added ~citar-denote-find-citation~ to find a citation in your Denote files.
